[package]
name = "i18n_langid_codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0.26"

serde = "1.0.160"
serde_yaml = "0.9.21"
